# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dominik\Documents\GitTGM\Py01\ipc\Game\server.ui'
#
# Created: Sun Jan  8 13:44:32 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(450, 501)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_101 = QtGui.QWidget(Form)
        self.widget_101.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_101.setObjectName("widget_101")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_101)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.widget_101)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.linePort = QtGui.QLineEdit(self.widget_101)
        self.linePort.setObjectName("linePort")
        self.horizontalLayout_2.addWidget(self.linePort)
        self.btnListen = QtGui.QPushButton(self.widget_101)
        self.btnListen.setObjectName("btnListen")
        self.horizontalLayout_2.addWidget(self.btnListen)
        self.listClients = QtGui.QListWidget(self.widget_101)
        self.listClients.setMaximumSize(QtCore.QSize(16777215, 50))
        self.listClients.setObjectName("listClients")
        self.horizontalLayout_2.addWidget(self.listClients)
        self.verticalLayout.addWidget(self.widget_101)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget_74 = QtGui.QWidget(Form)
        self.widget_74.setObjectName("widget_74")
        self.gridLayout.addWidget(self.widget_74, 7, 3, 1, 1)
        self.widget_2 = QtGui.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_71 = QtGui.QWidget(Form)
        self.widget_71.setObjectName("widget_71")
        self.gridLayout.addWidget(self.widget_71, 7, 0, 1, 1)
        self.widget_68 = QtGui.QWidget(Form)
        self.widget_68.setObjectName("widget_68")
        self.gridLayout.addWidget(self.widget_68, 6, 7, 1, 1)
        self.widget_73 = QtGui.QWidget(Form)
        self.widget_73.setObjectName("widget_73")
        self.gridLayout.addWidget(self.widget_73, 7, 2, 1, 1)
        self.widget_66 = QtGui.QWidget(Form)
        self.widget_66.setObjectName("widget_66")
        self.gridLayout.addWidget(self.widget_66, 6, 5, 1, 1)
        self.widget_69 = QtGui.QWidget(Form)
        self.widget_69.setObjectName("widget_69")
        self.gridLayout.addWidget(self.widget_69, 6, 8, 1, 1)
        self.widget_1 = QtGui.QWidget(Form)
        self.widget_1.setObjectName("widget_1")
        self.gridLayout.addWidget(self.widget_1, 0, 0, 1, 1)
        self.widget_87 = QtGui.QWidget(Form)
        self.widget_87.setObjectName("widget_87")
        self.gridLayout.addWidget(self.widget_87, 8, 6, 1, 1)
        self.widget_88 = QtGui.QWidget(Form)
        self.widget_88.setObjectName("widget_88")
        self.gridLayout.addWidget(self.widget_88, 8, 7, 1, 1)
        self.widget_89 = QtGui.QWidget(Form)
        self.widget_89.setObjectName("widget_89")
        self.gridLayout.addWidget(self.widget_89, 8, 8, 1, 1)
        self.widget_97 = QtGui.QWidget(Form)
        self.widget_97.setObjectName("widget_97")
        self.gridLayout.addWidget(self.widget_97, 9, 6, 1, 1)
        self.widget_98 = QtGui.QWidget(Form)
        self.widget_98.setObjectName("widget_98")
        self.gridLayout.addWidget(self.widget_98, 9, 7, 1, 1)
        self.widget_96 = QtGui.QWidget(Form)
        self.widget_96.setObjectName("widget_96")
        self.gridLayout.addWidget(self.widget_96, 9, 5, 1, 1)
        self.widget_95 = QtGui.QWidget(Form)
        self.widget_95.setObjectName("widget_95")
        self.gridLayout.addWidget(self.widget_95, 9, 4, 1, 1)
        self.widget_94 = QtGui.QWidget(Form)
        self.widget_94.setObjectName("widget_94")
        self.gridLayout.addWidget(self.widget_94, 9, 3, 1, 1)
        self.widget_86 = QtGui.QWidget(Form)
        self.widget_86.setObjectName("widget_86")
        self.gridLayout.addWidget(self.widget_86, 8, 5, 1, 1)
        self.widget_83 = QtGui.QWidget(Form)
        self.widget_83.setObjectName("widget_83")
        self.gridLayout.addWidget(self.widget_83, 8, 2, 1, 1)
        self.widget_90 = QtGui.QWidget(Form)
        self.widget_90.setObjectName("widget_90")
        self.gridLayout.addWidget(self.widget_90, 8, 9, 1, 1)
        self.widget_84 = QtGui.QWidget(Form)
        self.widget_84.setObjectName("widget_84")
        self.gridLayout.addWidget(self.widget_84, 8, 3, 1, 1)
        self.widget_85 = QtGui.QWidget(Form)
        self.widget_85.setObjectName("widget_85")
        self.gridLayout.addWidget(self.widget_85, 8, 4, 1, 1)
        self.widget_79 = QtGui.QWidget(Form)
        self.widget_79.setObjectName("widget_79")
        self.gridLayout.addWidget(self.widget_79, 7, 8, 1, 1)
        self.widget_80 = QtGui.QWidget(Form)
        self.widget_80.setObjectName("widget_80")
        self.gridLayout.addWidget(self.widget_80, 7, 9, 1, 1)
        self.widget_81 = QtGui.QWidget(Form)
        self.widget_81.setObjectName("widget_81")
        self.gridLayout.addWidget(self.widget_81, 8, 0, 1, 1)
        self.widget_91 = QtGui.QWidget(Form)
        self.widget_91.setObjectName("widget_91")
        self.gridLayout.addWidget(self.widget_91, 9, 0, 1, 1)
        self.widget_93 = QtGui.QWidget(Form)
        self.widget_93.setObjectName("widget_93")
        self.gridLayout.addWidget(self.widget_93, 9, 2, 1, 1)
        self.widget_99 = QtGui.QWidget(Form)
        self.widget_99.setObjectName("widget_99")
        self.gridLayout.addWidget(self.widget_99, 9, 8, 1, 1)
        self.widget_82 = QtGui.QWidget(Form)
        self.widget_82.setObjectName("widget_82")
        self.gridLayout.addWidget(self.widget_82, 8, 1, 1, 1)
        self.widget_78 = QtGui.QWidget(Form)
        self.widget_78.setObjectName("widget_78")
        self.gridLayout.addWidget(self.widget_78, 7, 7, 1, 1)
        self.widget_75 = QtGui.QWidget(Form)
        self.widget_75.setObjectName("widget_75")
        self.gridLayout.addWidget(self.widget_75, 7, 4, 1, 1)
        self.widget_92 = QtGui.QWidget(Form)
        self.widget_92.setObjectName("widget_92")
        self.gridLayout.addWidget(self.widget_92, 9, 1, 1, 1)
        self.widget_76 = QtGui.QWidget(Form)
        self.widget_76.setObjectName("widget_76")
        self.gridLayout.addWidget(self.widget_76, 7, 5, 1, 1)
        self.widget_77 = QtGui.QWidget(Form)
        self.widget_77.setObjectName("widget_77")
        self.gridLayout.addWidget(self.widget_77, 7, 6, 1, 1)
        self.widget_52 = QtGui.QWidget(Form)
        self.widget_52.setObjectName("widget_52")
        self.gridLayout.addWidget(self.widget_52, 5, 1, 1, 1)
        self.widget_53 = QtGui.QWidget(Form)
        self.widget_53.setObjectName("widget_53")
        self.gridLayout.addWidget(self.widget_53, 5, 2, 1, 1)
        self.widget_41 = QtGui.QWidget(Form)
        self.widget_41.setObjectName("widget_41")
        self.gridLayout.addWidget(self.widget_41, 4, 0, 1, 1)
        self.widget_60 = QtGui.QWidget(Form)
        self.widget_60.setObjectName("widget_60")
        self.gridLayout.addWidget(self.widget_60, 5, 9, 1, 1)
        self.widget_47 = QtGui.QWidget(Form)
        self.widget_47.setObjectName("widget_47")
        self.gridLayout.addWidget(self.widget_47, 4, 6, 1, 1)
        self.widget_56 = QtGui.QWidget(Form)
        self.widget_56.setObjectName("widget_56")
        self.gridLayout.addWidget(self.widget_56, 5, 5, 1, 1)
        self.widget_63 = QtGui.QWidget(Form)
        self.widget_63.setObjectName("widget_63")
        self.gridLayout.addWidget(self.widget_63, 6, 2, 1, 1)
        self.widget_38 = QtGui.QWidget(Form)
        self.widget_38.setObjectName("widget_38")
        self.gridLayout.addWidget(self.widget_38, 3, 7, 1, 1)
        self.widget_36 = QtGui.QWidget(Form)
        self.widget_36.setObjectName("widget_36")
        self.gridLayout.addWidget(self.widget_36, 3, 5, 1, 1)
        self.widget_48 = QtGui.QWidget(Form)
        self.widget_48.setObjectName("widget_48")
        self.gridLayout.addWidget(self.widget_48, 4, 7, 1, 1)
        self.widget_54 = QtGui.QWidget(Form)
        self.widget_54.setObjectName("widget_54")
        self.gridLayout.addWidget(self.widget_54, 5, 3, 1, 1)
        self.widget_57 = QtGui.QWidget(Form)
        self.widget_57.setObjectName("widget_57")
        self.gridLayout.addWidget(self.widget_57, 5, 6, 1, 1)
        self.widget_51 = QtGui.QWidget(Form)
        self.widget_51.setObjectName("widget_51")
        self.gridLayout.addWidget(self.widget_51, 5, 0, 1, 1)
        self.widget_45 = QtGui.QWidget(Form)
        self.widget_45.setObjectName("widget_45")
        self.gridLayout.addWidget(self.widget_45, 4, 4, 1, 1)
        self.widget_58 = QtGui.QWidget(Form)
        self.widget_58.setObjectName("widget_58")
        self.gridLayout.addWidget(self.widget_58, 5, 7, 1, 1)
        self.widget_65 = QtGui.QWidget(Form)
        self.widget_65.setObjectName("widget_65")
        self.gridLayout.addWidget(self.widget_65, 6, 4, 1, 1)
        self.widget_44 = QtGui.QWidget(Form)
        self.widget_44.setObjectName("widget_44")
        self.gridLayout.addWidget(self.widget_44, 4, 3, 1, 1)
        self.widget_37 = QtGui.QWidget(Form)
        self.widget_37.setObjectName("widget_37")
        self.gridLayout.addWidget(self.widget_37, 3, 6, 1, 1)
        self.widget_55 = QtGui.QWidget(Form)
        self.widget_55.setObjectName("widget_55")
        self.gridLayout.addWidget(self.widget_55, 5, 4, 1, 1)
        self.widget_59 = QtGui.QWidget(Form)
        self.widget_59.setObjectName("widget_59")
        self.gridLayout.addWidget(self.widget_59, 5, 8, 1, 1)
        self.widget_40 = QtGui.QWidget(Form)
        self.widget_40.setObjectName("widget_40")
        self.gridLayout.addWidget(self.widget_40, 3, 9, 1, 1)
        self.widget_49 = QtGui.QWidget(Form)
        self.widget_49.setObjectName("widget_49")
        self.gridLayout.addWidget(self.widget_49, 4, 8, 1, 1)
        self.widget_35 = QtGui.QWidget(Form)
        self.widget_35.setObjectName("widget_35")
        self.gridLayout.addWidget(self.widget_35, 3, 4, 1, 1)
        self.widget_72 = QtGui.QWidget(Form)
        self.widget_72.setObjectName("widget_72")
        self.gridLayout.addWidget(self.widget_72, 7, 1, 1, 1)
        self.widget_62 = QtGui.QWidget(Form)
        self.widget_62.setObjectName("widget_62")
        self.gridLayout.addWidget(self.widget_62, 6, 1, 1, 1)
        self.widget_42 = QtGui.QWidget(Form)
        self.widget_42.setObjectName("widget_42")
        self.gridLayout.addWidget(self.widget_42, 4, 1, 1, 1)
        self.widget_61 = QtGui.QWidget(Form)
        self.widget_61.setObjectName("widget_61")
        self.gridLayout.addWidget(self.widget_61, 6, 0, 1, 1)
        self.widget_46 = QtGui.QWidget(Form)
        self.widget_46.setObjectName("widget_46")
        self.gridLayout.addWidget(self.widget_46, 4, 5, 1, 1)
        self.widget_43 = QtGui.QWidget(Form)
        self.widget_43.setObjectName("widget_43")
        self.gridLayout.addWidget(self.widget_43, 4, 2, 1, 1)
        self.widget_64 = QtGui.QWidget(Form)
        self.widget_64.setObjectName("widget_64")
        self.gridLayout.addWidget(self.widget_64, 6, 3, 1, 1)
        self.widget_70 = QtGui.QWidget(Form)
        self.widget_70.setObjectName("widget_70")
        self.gridLayout.addWidget(self.widget_70, 6, 9, 1, 1)
        self.widget_50 = QtGui.QWidget(Form)
        self.widget_50.setObjectName("widget_50")
        self.gridLayout.addWidget(self.widget_50, 4, 9, 1, 1)
        self.widget_32 = QtGui.QWidget(Form)
        self.widget_32.setObjectName("widget_32")
        self.gridLayout.addWidget(self.widget_32, 3, 1, 1, 1)
        self.widget_12 = QtGui.QWidget(Form)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout.addWidget(self.widget_12, 1, 1, 1, 1)
        self.widget_19 = QtGui.QWidget(Form)
        self.widget_19.setObjectName("widget_19")
        self.gridLayout.addWidget(self.widget_19, 1, 8, 1, 1)
        self.widget_24 = QtGui.QWidget(Form)
        self.widget_24.setObjectName("widget_24")
        self.gridLayout.addWidget(self.widget_24, 2, 3, 1, 1)
        self.widget_21 = QtGui.QWidget(Form)
        self.widget_21.setObjectName("widget_21")
        self.gridLayout.addWidget(self.widget_21, 2, 0, 1, 1)
        self.widget_22 = QtGui.QWidget(Form)
        self.widget_22.setObjectName("widget_22")
        self.gridLayout.addWidget(self.widget_22, 2, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(Form)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_29 = QtGui.QWidget(Form)
        self.widget_29.setObjectName("widget_29")
        self.gridLayout.addWidget(self.widget_29, 2, 8, 1, 1)
        self.widget_4 = QtGui.QWidget(Form)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout.addWidget(self.widget_4, 0, 3, 1, 1)
        self.widget_10 = QtGui.QWidget(Form)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout.addWidget(self.widget_10, 0, 9, 1, 1)
        self.widget_67 = QtGui.QWidget(Form)
        self.widget_67.setObjectName("widget_67")
        self.gridLayout.addWidget(self.widget_67, 6, 6, 1, 1)
        self.widget_5 = QtGui.QWidget(Form)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout.addWidget(self.widget_5, 0, 4, 1, 1)
        self.widget_14 = QtGui.QWidget(Form)
        self.widget_14.setObjectName("widget_14")
        self.gridLayout.addWidget(self.widget_14, 1, 3, 1, 1)
        self.widget_25 = QtGui.QWidget(Form)
        self.widget_25.setObjectName("widget_25")
        self.gridLayout.addWidget(self.widget_25, 2, 4, 1, 1)
        self.widget_6 = QtGui.QWidget(Form)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout.addWidget(self.widget_6, 0, 5, 1, 1)
        self.widget_16 = QtGui.QWidget(Form)
        self.widget_16.setObjectName("widget_16")
        self.gridLayout.addWidget(self.widget_16, 1, 5, 1, 1)
        self.widget_13 = QtGui.QWidget(Form)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout.addWidget(self.widget_13, 1, 2, 1, 1)
        self.widget_17 = QtGui.QWidget(Form)
        self.widget_17.setObjectName("widget_17")
        self.gridLayout.addWidget(self.widget_17, 1, 6, 1, 1)
        self.widget_9 = QtGui.QWidget(Form)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout.addWidget(self.widget_9, 0, 8, 1, 1)
        self.widget_18 = QtGui.QWidget(Form)
        self.widget_18.setObjectName("widget_18")
        self.gridLayout.addWidget(self.widget_18, 1, 7, 1, 1)
        self.widget_8 = QtGui.QWidget(Form)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout.addWidget(self.widget_8, 0, 7, 1, 1)
        self.widget_11 = QtGui.QWidget(Form)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout.addWidget(self.widget_11, 1, 0, 1, 1)
        self.widget_26 = QtGui.QWidget(Form)
        self.widget_26.setObjectName("widget_26")
        self.gridLayout.addWidget(self.widget_26, 2, 5, 1, 1)
        self.widget_15 = QtGui.QWidget(Form)
        self.widget_15.setObjectName("widget_15")
        self.gridLayout.addWidget(self.widget_15, 1, 4, 1, 1)
        self.widget_20 = QtGui.QWidget(Form)
        self.widget_20.setObjectName("widget_20")
        self.gridLayout.addWidget(self.widget_20, 1, 9, 1, 1)
        self.widget_23 = QtGui.QWidget(Form)
        self.widget_23.setObjectName("widget_23")
        self.gridLayout.addWidget(self.widget_23, 2, 2, 1, 1)
        self.widget_7 = QtGui.QWidget(Form)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout.addWidget(self.widget_7, 0, 6, 1, 1)
        self.widget_34 = QtGui.QWidget(Form)
        self.widget_34.setObjectName("widget_34")
        self.gridLayout.addWidget(self.widget_34, 3, 3, 1, 1)
        self.widget_31 = QtGui.QWidget(Form)
        self.widget_31.setObjectName("widget_31")
        self.gridLayout.addWidget(self.widget_31, 3, 0, 1, 1)
        self.widget_27 = QtGui.QWidget(Form)
        self.widget_27.setObjectName("widget_27")
        self.gridLayout.addWidget(self.widget_27, 2, 6, 1, 1)
        self.widget_33 = QtGui.QWidget(Form)
        self.widget_33.setObjectName("widget_33")
        self.gridLayout.addWidget(self.widget_33, 3, 2, 1, 1)
        self.widget_30 = QtGui.QWidget(Form)
        self.widget_30.setObjectName("widget_30")
        self.gridLayout.addWidget(self.widget_30, 2, 9, 1, 1)
        self.widget_28 = QtGui.QWidget(Form)
        self.widget_28.setObjectName("widget_28")
        self.gridLayout.addWidget(self.widget_28, 2, 7, 1, 1)
        self.widget_39 = QtGui.QWidget(Form)
        self.widget_39.setObjectName("widget_39")
        self.gridLayout.addWidget(self.widget_39, 3, 8, 1, 1)
        self.widget_100 = QtGui.QWidget(Form)
        self.widget_100.setObjectName("widget_100")
        self.gridLayout.addWidget(self.widget_100, 9, 9, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widget = QtGui.QWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnShuffle = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShuffle.sizePolicy().hasHeightForWidth())
        self.btnShuffle.setSizePolicy(sizePolicy)
        self.btnShuffle.setObjectName("btnShuffle")
        self.horizontalLayout_4.addWidget(self.btnShuffle)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListen.setText(QtGui.QApplication.translate("Form", "Listen", None, QtGui.QApplication.UnicodeUTF8))
        self.btnShuffle.setText(QtGui.QApplication.translate("Form", "Shuffe Map", None, QtGui.QApplication.UnicodeUTF8))

