== A06: Design Patterns
Markus Reichl <markus@re1.at>
:revnumber: 1.0
:revdate: 2017-11-17
:revremark: Erster Entwurf
:version-label!:

Autor: {author}, Version: {revnumber}, {revdate}

=== Protokoll
==== Vorbereitung
. Neues Projekt
. Einrichtung grundlegender Module (`__main__.py`, `client.py`, `encrypt.py`, `server.py`)
. Einrichtung grundlegender Klassen und Methoden (`Client`, `Èncrypt`, `Server`)
. Vorbereitung des Decorator Pattern nach allgemeiner Definition (`EncryptDecorator`)

==== Entwicklung
===== Socket Chat
. Prototyp der Module client.py und server.py wurden auf Basis des Projekts https://github.com/mreichl-tgm/sew4/tree/master/06-pychat[06-pychat]
. Erweiterung der Module `client.py` und `server.py` um eigene `__main__` Methoden

[source,python]
----
{{server|client}}.py
if __name__ == "__main__":
    if len(sys.argv) > 3:       # Debug Mode
        Client(sys.argv[1], sys.argv[2], sys.argv[3])
    elif len(sys.argv) > 2:     # Port
        {{Server|Client}}(sys.argv[1], sys.argv[2])
    elif len(sys.argv) > 1:     # Host
        {{Server|Client}}(sys.argv[1])
    else:
        {{Server|Client}}()
----

===== Decorator Pattern
. Implementierung von Caesar und YetAnotherDraggyEncryption Verschlüsselungen anhand des Decorator Pattern.
. Einbinden der Dekoratoren in den Client
[source,python]
----
# Set encryption method
self.__crypt = YetAnotherDraggyEncryption(  # Encrypt using yet another draggy encryption
    Caesar(                                 # Encrypt using Caesar
        Encrypt()                           # Decorated Encrypt instance
    )
)
----

[source,python]
----
# Encrypt
self.__client.send(self.__crypt.encrypt("Message").encode())
# Decrypt
self.__crypt.decrypt(self.__client.recv(4096).decode())
----

Die Client Kommunikation wird nun verschlüsselt durchgeführt, wovon der Server jedoch nicht mitbekommt. :)
